#!/bin/bash

#strip header
#strip leading spaces
#swap spaces for commas

#run this on condo headnode

for year in {2015..2016}; do
    for month in {01..12}; do
      pbsacct "/home/baber/LAS_Reports/$year$month??" | tail -n +13 | sed 's/^ *//g' | tr -s ' ' ',' | grep -v -e baber -e snehring -e campbell  > "./data/condo_usage/condo_las_$year$month"
    done;
done;

#next step is condo_usage_by_lab_ad_lookup
