#!/bin/bash

#                          Wallclock          Average Average
#Username    Group   #jobs      days  Percent  #nodes  q-days  Full name
#--------    -----   ----- ---------  ------- ------- -------  ---------

#strip header
#strip leading spaces
#swap spaces for commas

#run this on condo headnode

for year in {2015..2016}; do
    for month in {01..12}; do
      pbsacct "/home/baber/LAS_Reports/$year$month??" | tail -n +13 | sed 's/^ *//g' | tr -s ' ' ',' > "./data/condo_usage/condo_las_$year$month"
    done;
done;

#cat condo_las_201608 | cut -f 1 -d ',' | xargs -I user ldapsearch -Q "(cn=user)" memberOf | grep '\-lab' | cut -f 2 -d ':' | cut -f 1 -d ',' | cut -f 2 -d '='
