#!/bin/bash

#                          Wallclock          Average Average
#Username    Group   #jobs      days  Percent  #nodes  q-days  Full name
#--------    -----   ----- ---------  ------- ------- -------  ---------

#run this on somewhere with ldapsearch available, and a copy of the datafile output from condo

for year in {2015..2016}; do
    for month in {01..12}; do
      #cat "./data/condo_usage/condo_las_$year$month" | cut -f 1 -d ',' | xargs -I user ldapsearch -Q "(cn=user)" memberOf | grep '\-lab' | cut -f 2 -d ':' | cut -f 1 -d ',' | cut -f 2 -d '='
      while read line; do
        lab_group=$(echo $line | cut -f 1 -d ',' | xargs -I user ldapsearch -Q "(cn=user)" memberOf | grep '\-lab' | cut -f 2 -d ':' | cut -f 1 -d ',' | cut -f 2 -d '=')
        user=$(echo $line | cut -f 1 -d ',')
        num_jobs=$(echo $line | cut -f 3 -d ',')
        walllclock_days=$(echo $line | cut -f 4 -d ',')
        avg_nodes=$(echo $line | cut -f 6 -d ',')
        avg_qdays=$(echo $line | cut -f 7 -d ',')
        echo "$lab_group,$user,$num_jobs,$walllclock_days,$avg_nodes,$avg_qdays,$year,$month" >> ./data/condo_usage/lab_summary.csv

      done < "./data/condo_usage/condo_las_$year$month"
    done;
done;
